import Foundation

enum LuaScriptGenerator {
    static func generate(from macro: MacroFile) -> String {
        var script = """
        -- AutoTouch-compatible macro script
        -- Generated by MacroApp on \(DateFormatter.localizedString(from: Date(), dateStyle: .medium, timeStyle: .medium))
        -- Macro: \(macro.name)
        -- Total actions: \(macro.actions.count)
        -- Screen size: \(Int(macro.screenSize.width))x\(Int(macro.screenSize.height))

        local screenWidth = \(Int(macro.screenSize.width))
        local screenHeight = \(Int(macro.screenSize.height))

        function main()
        """

        for (index, action) in macro.actions.enumerated() {
            script += "\n"
            switch action.type {
            case .tap:
                if let point = action.startPoint {
                    script += "    -- Action \(index + 1): Tap at (\(Int(point.x)), \(Int(point.y)))\n"
                    script += "    usleep(\(Int(action.delay * 1_000_000)))\n"
                    script += "    touchDown(0, \(Int(point.x)), \(Int(point.y)))\n"
                    script += "    usleep(50000)\n"
                    script += "    touchUp(0, \(Int(point.x)), \(Int(point.y)))\n"
                }
            case .swipe:
                if let start = action.startPoint, let end = action.endPoint {
                    let steps = max(10, Int(action.duration * 60))
                    let stepDelay = Int(action.duration / Double(steps) * 1_000_000)
                    script += "    -- Action \(index + 1): Swipe from (\(Int(start.x)), \(Int(start.y))) to (\(Int(end.x)), \(Int(end.y)))\n"
                    script += "    usleep(\(Int(action.delay * 1_000_000)))\n"
                    script += "    touchDown(0, \(Int(start.x)), \(Int(start.y)))\n"
                    script += "    for i = 1, \(steps) do\n"
                    script += "        usleep(\(stepDelay))\n"
                    script += "        local x = math.floor(\(Int(start.x)) + (\(Int(end.x)) - \(Int(start.x))) * i / \(steps))\n"
                    script += "        local y = math.floor(\(Int(start.y)) + (\(Int(end.y)) - \(Int(start.y))) * i / \(steps))\n"
                    script += "        touchMove(0, x, y)\n"
                    script += "    end\n"
                    script += "    usleep(50000)\n"
                    script += "    touchUp(0, \(Int(end.x)), \(Int(end.y)))\n"
                }
            case .longPress:
                if let point = action.startPoint {
                    script += "    -- Action \(index + 1): Long press at (\(Int(point.x)), \(Int(point.y))) for \(String(format: "%.2f", action.duration))s\n"
                    script += "    usleep(\(Int(action.delay * 1_000_000)))\n"
                    script += "    touchDown(0, \(Int(point.x)), \(Int(point.y)))\n"
                    script += "    usleep(\(Int(action.duration * 1_000_000)))\n"
                    script += "    touchUp(0, \(Int(point.x)), \(Int(point.y)))\n"
                }
            case .keyPress:
                if let key = action.key {
                    script += "    -- Action \(index + 1): Key press '\(key)'\n"
                    script += "    usleep(\(Int(action.delay * 1_000_000)))\n"
                    script += "    keyPress(\"\(key)\")\n"
                }
            case .wait:
                script += "    -- Action \(index + 1): Wait \(String(format: "%.2f", action.duration))s\n"
                script += "    usleep(\(Int(action.duration * 1_000_000)))\n"
            case .scroll:
                if let delta = action.scrollDelta {
                    script += "    -- Action \(index + 1): Scroll by \(Int(delta))\n"
                    script += "    usleep(\(Int(action.delay * 1_000_000)))\n"
                    script += "    scroll(\(Int(delta)))\n"
                }
            }
        }

        script += """

        end

        main()
        """

        return script
    }

    static func parseFromLua(_ script: String) -> [MacroAction] {
        var actions: [MacroAction] = []
        let scanner = Scanner(string: script)
        var lastDelay: TimeInterval = 0

        while !scanner.isAtEnd {
            let _ = scanner.scanUpToString("touchDown(")
            guard scanner.scanString("touchDown(") != nil else {
                let _ = scanner.scanUpToString("usleep(")
                if scanner.scanString("usleep(") != nil {
                    if let microseconds = scanner.scanDouble() {
                        lastDelay = microseconds / 1_000_000
                    }
                }
                continue
            }

            guard let fingerId = scanner.scanInt(),
                  scanner.scanString(",") != nil,
                  let x = scanner.scanDouble(),
                  scanner.scanString(",") != nil,
                  let y = scanner.scanDouble() else { continue }

            let point = CGPoint(x: x, y: y)

            let remaining = scanner.string[scanner.currentIndex...]
            if remaining.contains("touchMove") {
                var endPoint = point
                var sweep = false
                while !scanner.isAtEnd {
                    let _ = scanner.scanUpToString("touchMove(")
                    if scanner.scanString("touchMove(") != nil {
                        if let _ = scanner.scanInt(),
                           scanner.scanString(",") != nil,
                           let mx = scanner.scanDouble(),
                           scanner.scanString(",") != nil,
                           let my = scanner.scanDouble() {
                            endPoint = CGPoint(x: mx, y: my)
                            sweep = true
                        }
                    }
                    if scanner.scanString("touchUp(") != nil { break }
                    scanner.currentIndex = scanner.string.index(after: scanner.currentIndex)
                }
                if sweep {
                    actions.append(.swipe(from: point, to: endPoint, duration: 0.3, delay: lastDelay))
                }
            } else {
                let _ = scanner.scanUpToString("touchUp(")
                actions.append(.tap(at: point, delay: lastDelay))
            }
            lastDelay = 0
        }

        return actions
    }
}
